[alias]
kbuild = """build --target x86_64-bmos.json -Z build-std=core,alloc \
    -Z build-std-features=compiler-builtins-mem"""
kclippy = """clippy --target x86_64-bmos.json -Z build-std=core,alloc \
    -Z build-std-features=compiler-builtins-mem"""
