[alias]
mkboot = "run --package=boot --target=aarch64-apple-darwin"

[build]
target = "x86_64-bmos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
