[alias]
mkboot = "run --package=boot --target=x86_64-unknown-linux-gnu"

[build]
target = "x86_64-bmos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
